taskchampion/taskchampion

Cargo.lock, Cargo.toml, README.md, docs/development-notes.md, src/bin/task.rs, tests/operation_transform_invariant.rs, tests/sync.rs, tests/sync_action_sequences.rs
=> rename to taskchampion

.taskcluster.yml, src/task/mod.rs
..and the checks API. Fixes #3.
=> use a v1 .taskcluster.yml

Cargo.lock, cli/Cargo.toml, cli/src/cmd/list.rs, cli/src/cmd/pending.rs, cli/src/lib.rs, cli/src/table.rs
=> use prettytable for tabular outputs

cli/src/cmd/info.rs, cli/src/cmd/mod.rs, cli/src/cmd/shared.rs, taskchampion/src/task.rs
=> add an 'info' subcommand

Cargo.lock, cli/Cargo.toml, cli/src/cmd/add.rs, cli/src/cmd/shared.rs, taskchampion/src/lib.rs
=> export the Uuid type from taskchampion

cli/src/cmd/info.rs, cli/src/cmd/list.rs, cli/src/cmd/shared.rs, taskchampion/src/replica.rs, taskchampion/src/taskdb.rs, taskchampion/src/taskstorage/inmemory.rs, taskchampion/src/taskstorage/kv.rs, taskchampion/src/taskstorage/mod.rs
=> Update handling of working set and show id's more widely

.taskcluster.yml, cli/src/cmd/pending.rs, cli/src/cmd/shared.rs, sync-server/src/lib.rs, taskchampion/src/lib.rs, taskchampion/src/replica.rs, taskchampion/src/task.rs, taskchampion/src/taskdb.rs, taskchampion/src/taskstorage/inmemory.rs, taskchampion/src/taskstorage/kv.rs, taskchampion/src/taskstorage/mod.rs, taskchampion/src/taskstorage/operation.rs
Clippy seems not to play nicely with workspaces, so this could be annoying..
=> add cargo clippy to CI

cli/src/cmd/add.rs, taskchampion/src/replica.rs
=> replica.new_task now invents its own uuid

Cargo.lock, sync-server/Cargo.toml, sync-server/src/api/add_version.rs, sync-server/src/api/get_child_version.rs, sync-server/src/server.rs, sync-server/src/storage/mod.rs
=> do not require taskchampion from sync-server

cli/src/cmd/shared.rs, docs/src/usage.md, taskchampion/src/taskstorage/kv.rs
=> take configuration in env vars temporarily

cli/src/cmd/mod.rs, cli/src/cmd/modify.rs
=> add 'task modify' (that can only modify description right now)

Cargo.lock, cli/Cargo.toml, cli/src/cmd/add.rs, cli/src/cmd/gc.rs, cli/src/cmd/info.rs, cli/src/cmd/list.rs, cli/src/cmd/modify.rs, cli/src/cmd/pending.rs, cli/src/cmd/shared.rs, cli/src/cmd/sync.rs, cli/src/lib.rs, cli/src/settings.rs, docs/src/usage.md, taskchampion/src/config.rs, taskchampion/src/lib.rs, taskchampion/src/replica.rs, taskchampion/src/server/local.rs, taskchampion/src/server/mod.rs, taskchampion/src/taskdb.rs, taskchampion/src/taskstorage/mod.rs
There are some things I don't like here:
* there's no way to specify allowed parameters and reject the rest
* there's no way to dump the configuration (short of writing an iterator over Value, which is tricky since it's partially opaque)
But, the file is simple enough so far that we could probably swap something in without changing the interface, so let's go with it.
Fixes #9.
=> Support configuration of the cli

cli/src/cmd/debug.rs, cli/src/cmd/list.rs, cli/src/cmd/mod.rs, cli/src/cmd/pending.rs, cli/src/cmd/start.rs, cli/src/cmd/stop.rs, docs/src/tasks.md, taskchampion/src/task.rs
=> Add start and stop commands

Cargo.lock, cli/Cargo.toml, cli/src/bin/task.rs, cli/src/cmd/shared.rs, cli/src/settings.rs, docs/src/usage.md, sync-server/Cargo.toml, sync-server/src/main.rs, sync-server/src/server.rs, taskchampion/Cargo.toml, taskchampion/src/replica.rs, taskchampion/src/task.rs, taskchampion/src/taskdb.rs
=> use log and env_logger, and add some logging around sync

cli/src/argparse/args.rs, cli/src/argparse/modification.rs, cli/src/invocation/cmd/info.rs, cli/src/invocation/modify.rs, cli/src/macros.rs, docs/src/tasks.md, taskchampion/src/lib.rs, taskchampion/src/task.rs
```
task add foo +bar
task 1 modify -bar +bing
task 1 info
```
=> Implement tags in the Replica API and the CLI

cli/src/argparse/filter.rs, cli/src/argparse/mod.rs, cli/src/argparse/modification.rs, cli/src/argparse/subcommand.rs, cli/src/invocation/filter.rs, cli/src/invocation/modify.rs, cli/src/usage.rs
=> Support filtering by tags

cli/src/invocation/cmd/add.rs, cli/src/invocation/cmd/gc.rs, cli/src/invocation/cmd/sync.rs, cli/src/invocation/cmd/version.rs, cli/src/invocation/filter.rs, cli/src/invocation/mod.rs, cli/src/invocation/modify.rs, cli/src/lib.rs, cli/src/usage.rs, sync-server/src/main.rs, taskchampion/src/lib.rs, taskchampion/src/task.rs
=> Fix clippy warnings and make them all errors

cli/src/argparse/args.rs, cli/src/argparse/command.rs, cli/src/argparse/filter.rs, cli/src/argparse/modification.rs, cli/src/argparse/subcommand.rs, cli/src/invocation/cmd/add.rs, cli/src/invocation/cmd/help.rs, cli/src/invocation/cmd/info.rs, cli/src/invocation/cmd/list.rs, cli/src/invocation/cmd/modify.rs, cli/src/invocation/filter.rs, cli/src/macros.rs
=> use a s!(..) shorthand in CLI tests

cli/src/argparse/mod.rs, cli/src/argparse/report.rs, cli/src/argparse/subcommand.rs, cli/src/invocation/cmd/list.rs, cli/src/invocation/mod.rs, cli/src/invocation/report.rs, taskchampion/src/task.rs
Fixes #119.
This isn't much, but at least gets the basic components in place: filter, columns, sort order.
=> implement generic report generation

cli/src/invocation/mod.rs, cli/src/settings.rs, docs/src/usage.md
=> Default to a local server, so `task sync` works out of the box

cli/src/argparse/filter.rs, cli/src/invocation/cmd/report.rs, cli/src/invocation/mod.rs, cli/src/invocation/report.rs, cli/src/report.rs, cli/src/settings.rs
Fixes #120.
I'll open follow-ups for automatic documentation of built-in reports.
=> Parse reports from config, with defaults

cli/src/invocation/filter.rs, cli/src/invocation/report.rs, taskchampion/src/replica.rs, taskchampion/src/task.rs, taskchampion/src/taskdb.rs, taskchampion/src/taskstorage/inmemory.rs, taskchampion/src/taskstorage/kv.rs, taskchampion/src/taskstorage/mod.rs
Rust handles this well.  Fixes #125.
=> Always pass Uuids by value

cli/src/argparse/args.rs, docs/src/SUMMARY.md, docs/src/tags.md, taskchampion/src/task.rs
=> Adjust Tag syntax to match TaskWarrior

cli/src/invocation/mod.rs, cli/src/invocation/test.rs, docs/src/storage.md, taskchampion/src/config.rs, taskchampion/src/lib.rs, taskchampion/src/replica.rs, taskchampion/src/server/config.rs, taskchampion/src/server/mod.rs, taskchampion/src/storage/config.rs, taskchampion/src/storage/inmemory.rs, taskchampion/src/storage/kv.rs, taskchampion/src/storage/mod.rs, taskchampion/src/storage/operation.rs, taskchampion/src/task.rs, taskchampion/src/taskdb.rs
This will be a breaking change, but hey we're at 0.x so that's fine.
Fixes #144.
=> Reorganize the 'taskchampion' crate

Cargo.lock, cli/Cargo.toml, cli/src/invocation/cmd/sync.rs, cli/src/invocation/test.rs, sync-server/Cargo.toml, sync-server/src/storage/kv.rs, taskchampion/Cargo.toml, taskchampion/src/server/local.rs, taskchampion/src/storage/kv.rs
=> Replace tempfile with tempdir

cli/src/invocation/report.rs
=> remove debugging prints

cli/src/argparse/config.rs, cli/src/invocation/cmd/config.rs
=> add 'ta config path'

.github/workflows/checks.yml, .github/workflows/tests.yml, taskchampion/src/lib.rs
=> Define and test an MSRV

cli/src/invocation/cmd/modify.rs, cli/src/invocation/mod.rs, cli/src/invocation/modify.rs
=> Summarize tasks nicely in console output

Cargo.lock, cli/Cargo.toml, cli/src/argparse/args/arg_matching.rs, cli/src/argparse/args/misc.rs, cli/src/argparse/args/tags.rs, cli/src/argparse/filter.rs, cli/src/argparse/modification.rs, cli/src/bin/usage-docs.rs, cli/src/invocation/filter.rs, cli/src/invocation/modify.rs, cli/src/macros.rs, cli/src/usage.rs
=> produce Tag instances in the parser

cli/src/argparse/args/arg_matching.rs
This is correct, but leaves a lot of room for improvement in terms of error handling (#253).
=> Treat partially-matched arguments as an error

Cargo.lock, cli/Cargo.toml, cli/src/invocation/cmd/modify.rs, cli/src/invocation/mod.rs, cli/src/invocation/util.rs, cli/src/settings/settings.rs, docs/src/config-file.md
=> Add confirmation prompts for modifications of lots of tasks

cli/src/lib.rs
=> Fix arg parsing on Windows

.github/workflows/tests.yml
..hopefully. As per https://github.com/taskchampion/taskchampion/issues/274
=> CI tests on Windows+macOS

cli/src/settings/settings.rs
=> Create a new doc if necessary in `ta config set`

.github/workflows/checks.yml, .github/workflows/tests.yml, cli/src/invocation/mod.rs, cli/src/invocation/modify.rs, cli/src/settings/report.rs, cli/src/settings/settings.rs, sync-server/src/storage/kv.rs
=> Fix clippy and only run it with the MSRV

.github/workflows/checks.yml, .github/workflows/publish-docs.yml, .github/workflows/tests.yml
=> use actions/cache@v2

build-docs.sh, cli/src/argparse/args/time.rs, taskchampion/src/lib.rs, taskchampion/src/replica.rs, taskchampion/src/storage/sqlite.rs, taskchampion/src/task/mod.rs, taskchampion/src/task/tag.rs, taskchampion/src/task/task.rs
=> Docs update

.github/workflows/checks.yml, cli/src/settings/util.rs
(I also bumped checkout  to v2 on the blind assumption that's better)
=> add a cargo-fmt job to CI

docs/src/tasks.md, taskchampion/src/task/task.rs
This aligns with the Taskwarrior data model.
Fixes #312
=> Use `tag_<tag>` instead of `tag.<tag>`

cli/src/invocation/cmd/add.rs
=> Fix application of modifications during 'ta add'

taskchampion/src/replica.rs, taskchampion/src/task/status.rs
=> use strum_macros::Display to display Status

docs/src/tasks.md, taskchampion/src/replica.rs, taskchampion/src/task/task.rs
=> add 'entry' key to tasks when created

lib/src/lib.rs, lib/src/replica.rs, lib/src/server.rs, lib/src/string.rs, lib/src/task.rs, lib/src/uda.rs, xtask/src/main.rs
=> fix some clippy warnings, and make them errors for taskchampion-lib

integration-tests/src/bindings_tests/replica.c, lib/src/replica.rs, lib/taskchampion.h, taskchampion/src/replica.rs, taskchampion/src/storage/inmemory.rs, taskchampion/src/storage/mod.rs, taskchampion/src/storage/sqlite.rs, taskchampion/src/taskdb/mod.rs
This is useful to know if a sync is required.
=> Add `Replica.num_local_operations`
