taskchampion/taskchampion

- taskchampion/src/taskstorage/inmemory.rs
- taskchampion/src/taskstorage/kv.rs
- taskchampion/src/taskstorage/mod.rs
Items are only removed from the working set when it is rebuilt, so this
method is unnecessary.
Fixes #34.
> Remove `remove_from_working_set` method.

- Cargo.lock
- cli/src/cmd/shared.rs
- sync-server/src/api/add_version.rs
- sync-server/src/api/get_child_version.rs
- sync-server/src/server.rs
- sync-server/src/storage/inmemory.rs
- sync-server/src/storage/mod.rs
- taskchampion/Cargo.toml
- taskchampion/src/server/mod.rs
- taskchampion/src/server/remote.rs
This works against taskchampion-sync-server.
I'm not sure how best to test it, though, without introducing a *lot* more complexity that this (super short!) implementation.  Running taskchampion-sync-server directly would be hard (probably in another process, which means killing that process after the test finishes), require complex synchronization of server startup (can't contact the server until it's listening!).  And then how do we assert the results?
Mocking out ureq would double the size of the non-test code.
Building a mock server would introduce more untested code than the code we're trying to test.
So, I think this will stay untested for now.
> Add RemoteServer to the taskchampion crate

- cli/src/cmd/append.rs
- cli/src/cmd/mod.rs
- cli/src/cmd/prepend.rs
This currently uses format!() which may not be the best option. Fixes #88
I'm unsure how to set up an existing test task to ensure the test does actually append and prepend as desired.
> subcommands: prepend and append to description

- Cargo.lock
- cli/Cargo.toml
- cli/src/invocation/mod.rs
- docs/src/usage.md
- taskchampion/Cargo.toml
- taskchampion/src/config.rs
- taskchampion/src/server/mod.rs
- taskchampion/src/server/remote/crypto.rs
- taskchampion/src/server/remote/mod.rs
This uses tindercrypt, which is a pretty thin wrapper around `ring` that just applies some sane defaults.
> Encrypt content sent to the server.

- cli/src/invocation/mod.rs
- docs/src/sync-protocol.md
- sync-server/src/api/add_version.rs
- sync-server/src/api/get_child_version.rs
- sync-server/src/api/mod.rs
- sync-server/src/server.rs
- sync-server/src/storage/inmemory.rs
- sync-server/src/storage/kv.rs
- sync-server/src/storage/mod.rs
- taskchampion/src/config.rs
- taskchampion/src/server/mod.rs
- taskchampion/src/server/remote/mod.rs
This works more like an API key than a userid.  So, let's not keep it in the URL.
Fixes #60.
> Use a single secret value to identify clients

- cli/src/argparse/args.rs
- cli/src/argparse/filter.rs
- cli/src/argparse/mod.rs
- cli/src/argparse/subcommand.rs
- cli/src/invocation/cmd/mod.rs
- cli/src/invocation/cmd/report.rs
- cli/src/invocation/filter.rs
- cli/src/invocation/mod.rs
- cli/src/invocation/report.rs
- cli/src/lib.rs
- cli/src/report.rs
This substantially refactors filtering, too.  It was a one-thing-leads-to-another situation: 
* named reports have filters, and users can give additional filter command-line arguments, so we need a way to combine those
* combining filters with universes is hard, so let's limit the scope of universes
* now we have more conditions, so let's make command-line syntax for them (well, we already have syntax for Condition::IdList..)
I'll file a few followups.
> Use named reports

- cli/src/invocation/cmd/gc.rs
- cli/src/invocation/filter.rs
- cli/src/invocation/report.rs
- taskchampion/src/replica.rs
- taskchampion/src/taskdb.rs
- taskchampion/src/taskstorage/inmemory.rs
- taskchampion/src/taskstorage/kv.rs
- taskchampion/src/taskstorage/mod.rs
This should ensure that in most cases, any pending task is in the working set.  That's critical for the filter optimization that just scans the working set.
It can miss the case where a task is marked as not pending, but that just leaves an extra task in the set.  
Fixes #68.
> Automatically add new pending tasks to working set after sync

- cli/src/invocation/cmd/add.rs
- cli/src/invocation/cmd/info.rs
- cli/src/invocation/filter.rs
- cli/src/invocation/report.rs
- taskchampion/src/lib.rs
- taskchampion/src/replica.rs
- taskchampion/src/workingset.rs
Rather than allow addressing tasks either by working set ID or uuid,
with attendant performance issues, this moves the API for the working
set to a single struct that just serves as a 1-1 mapping of indexes to
UUIDs.  It's up to the caller to use this information.
This is slightly less useful for callers that wish to address tasks by index.  However, I think most users of this crate -- aside from taskchampion-cli -- will not care about the working set and will not need to do this.
> Centralize API for working set to a single struct

- .github/dependabot.yml
This should get dependabot working again.  Somewhere in the GitHub UI, there's a place where it reports errors from dependabot, and that showed that the correct word is "cargo" and not "rust".  I can't find that UI again, though!
Refs #165.
> use the correct 'package-ecosystem' config

- cli/src/argparse/mod.rs
- cli/src/invocation/mod.rs
- sync-server/src/main.rs
- sync-server/src/storage/kv.rs
- sync-server/src/storage/mod.rs
- taskchampion/src/errors.rs
- taskchampion/src/replica.rs
- taskchampion/src/storage/config.rs
- taskchampion/src/storage/kv.rs
- taskchampion/src/storage/mod.rs
- taskchampion/src/storage/operation.rs
- taskchampion/src/taskdb.rs
Unnecessary wraps are fixed in one place and ignored in another (where they're required for a callback).
Capitalization fixed (note that this is an API-breaking change for KVStorage, but we're getting rid of that in favor of SQLite anyway)
> fix some clippy stuff

- docs/src/sync-protocol.md
- sync-server/src/api/add_version.rs
- sync-server/src/api/get_child_version.rs
- taskchampion/src/server/remote/mod.rs
This is an incompatible change to the sync-server protocol.
Fixes #151.
> [breaking] Include /v1/ in the sync-server paths

- cli/src/invocation/cmd/sync.rs
- taskchampion/src/replica.rs
- taskchampion/src/storage/kv.rs
- taskchampion/src/taskdb.rs
- taskchampion/src/workingset.rs
I ran into an issue in day-to-day use where the code tried to set working-set index 0 to None.  First, there is no working set index 0; and second, setting a working-set index to None that is already None should be valid.  So, all of that is fixed, with some extra checks.
> Fix a working set rebuild bug

- cli/Cargo.toml
- cli/build.rs
- cli/src/invocation/cmd/version.rs
As per #241
Output is something like:
```
TaskChampion 0.3.0 (git rev: 1d6c3aa)
```
> Include git HEAD rev in version output

- cli/src/argparse/filter.rs
- cli/src/argparse/subcommand.rs
This filter can either be `*` or some "real" filter.  But an empty set
of arguments no longer automatically matches all tasks.
Fixes #177.
> Require a filter be specified for modifications

- cli/Cargo.toml
Seems kind of handy:
```
$ cd taskchampion
$ cargo run
```
Previously this would have errored with
```
error: `cargo run` could not determine which binary to run. Use the `--bin` option to specify a binary, or the `default-run` manifest key.
```
Everything else should still function as before, e.g:
```
$ cargo run --bin ta
$ cargo run --bin taskchampion-sync-server
$ cd sync-server
$ cargo run # runs sync-server
```
> Make 'cargo run' run ta binary

- cli/src/argparse/command.rs
Minor thing but makes the help text a lot less visually dense (when doing `cargo run` at least)
```
TaskChampion subcommands:
ta version
Show the version of the TaskChampion binary
ta config set <key> <value>
Update Taskchampion configuration file to set key = value
```
..which was previously:
```
TaskChampion subcommands:
target/debug/ta version
Show the version of the TaskChampion binary
target/debug/ta config set <key> <value>
Update Taskchampion configuration file to set key = value
```
> Remove path from ta command in usage text

- Cargo.lock
- cli/Cargo.toml
- cli/build.rs
- cli/src/invocation/cmd/version.rs
- cli/src/lib.rs
The existing invocation of `git` wasn't working for me:
```
cleave ~/p/taskchampion [use-built] $ ta version                                                                                                                                                                                                                                                  
TaskChampion 0.3.0 (git rev: )                                                                                                                   
```
this PR does about the same thing, but outsourcing the version determination to Someone Else's Crate.
> Use `built` to determine version information

- Cargo.lock
- cli/src/invocation/report.rs
- docs/src/tags.md
- taskchampion/Cargo.toml
- taskchampion/src/task.rs
- taskchampion/src/task/annotation.rs
- taskchampion/src/task/mod.rs
- taskchampion/src/task/priority.rs
- taskchampion/src/task/status.rs
- taskchampion/src/task/tag.rs
- taskchampion/src/task/task.rs
Notably, nothing changes for the CLI -- this is entirely within the taskchampion crate, and everything outside just sees all-caps tags.
Fixes #80.
> Add support for synthetic tags

- sync-server/src/api/get_child_version.rs
- sync-server/src/bin/taskchampion-sync-server.rs
Fixes #99.
There's an ugly macro hack in here to work around actix-web's un-ergonomics, but it's not too bad.
> Add cache-control headers to API responses

- cli/src/argparse/modification.rs
- cli/src/argparse/subcommand.rs
- cli/src/invocation/cmd/info.rs
- cli/src/invocation/modify.rs
- docs/src/tasks.md
- taskchampion/src/lib.rs
- taskchampion/src/task/annotation.rs
- taskchampion/src/task/task.rs
This matches the taskwarrior task model for annotations.
Note that I didn't support `ta denotate`.  If we feel that's necessary, we can make an issue to do it in a followup (outside of 0.5.0).
> Add support for annotations

- .github/workflows/checks.yml
It looks like we were just using an older clippy?
```
funk ~/p/taskchampion [issue322*] $ cargo clean 
funk ~/p/taskchampion [issue322*] $ cargo clippy 
Compiling libc v0.2.97              
Compiling proc-macro2 v1.0.27      
...
Compiling built v0.5.1
Checking replica-server-tests v0.4.1 (/home/dustin/p/taskchampion/replica-server-tests)
Compiling taskchampion-cli v0.4.1 (/home/dustin/p/taskchampion/cli)
Finished dev [unoptimized + debuginfo] target(s) in 1m 44s
funk ~/p/taskchampion [issue322] $ cargo version
cargo 1.57.0 (b2e52d7ca 2021-10-21)
```
> Update clippy toolchain to 1.57

- docs/src/tasks.md
- taskchampion/src/replica.rs
- taskchampion/src/task/task.rs
This definition matches how TaskWarrior uses the same key.
Fixes #327.
> Support an 'end' key in task maps

- Cargo.lock
- lib/Cargo.toml
- lib/src/uuid.rs
I spotted this while poking around elsewhere -- taskchampion-lib exposes a literal constant so that cbindgen can reflect its value into the header file.  But it was using a constant from the uuid crate in the code.  They had the same value, so it didn't make a big difference, but (a) this is cleaner and (b) this avoids taskchampion-lib requiring uuid directly.
> use TC_UUID_STRING_BYTES constant directly

- Cargo.lock
Note that the risk from this vulnerability was minimal for this project.
> Address RUSTSEC-2022-0013.

- Cargo.lock
- cli/src/argparse/subcommand.rs
- cli/src/invocation/cmd/gc.rs
- docs/src/taskdb.md
- integration-tests/Cargo.toml
- integration-tests/tests/update-and-delete-sync.rs
- taskchampion/src/replica.rs
- taskchampion/src/task/task.rs
This expires _deleted_ tasks 180 days after their last modification.
In most cases, users' tasks will stay around forever, as they are marked "completed" and not "deleted", but users who wish to keep their task list short can do something like `ta +COMPLETED delete` periodically.
> Add support for expiration

- integration-tests/src/bindings_tests/task.c
- lib/src/annotation.rs
- lib/src/kv.rs
- lib/src/replica.rs
- lib/src/string.rs
- lib/src/task.rs
- lib/src/traits.rs
- lib/src/uda.rs
- lib/src/uuid.rs
- lib/taskchampion.h
This introduces `tc_task_list_take`, supporting taking ownership of an
item in a task list.
TCTaskList is the only pointer list, but this is a generic and could be
used for other types.
> Allow taking from pointer lists

- Cargo.lock
- cli/Cargo.toml
- cli/src/argparse/args/colon.rs
- cli/src/argparse/args/time.rs
- cli/src/argparse/mod.rs
- cli/src/argparse/modification.rs
- cli/src/invocation/cmd/import_tdb2.rs
- cli/src/invocation/cmd/import_tw.rs
- cli/src/invocation/modify.rs
- cli/src/invocation/report.rs
- integration-tests/Cargo.toml
- integration-tests/tests/update-and-delete-sync.rs
- lib/Cargo.toml
- lib/src/annotation.rs
- lib/src/atomic.rs
- lib/src/task.rs
- taskchampion/src/lib.rs
The chrono types are central to use of TC, so this will help consumers
of the TC crate to avoid dependency conflicts.
> Re-export the chrono crate from taskchampion.

- cli/src/argparse/args/colon.rs
- cli/src/argparse/args/idlist.rs
- cli/src/argparse/args/mod.rs
- cli/src/argparse/modification.rs
- cli/src/invocation/cmd/add.rs
- cli/src/invocation/cmd/info.rs
- cli/src/invocation/cmd/modify.rs
- cli/src/invocation/mod.rs
- cli/src/invocation/modify.rs
- cli/src/invocation/report.rs
- cli/src/macros.rs
- integration-tests/src/bindings_tests/task.c
- lib/src/task.rs
- lib/taskchampion.h
- taskchampion/src/depmap.rs
- taskchampion/src/lib.rs
- taskchampion/src/macros.rs
- taskchampion/src/replica.rs
- taskchampion/src/task/tag.rs
- taskchampion/src/task/task.rs
The TC API part of this is, so far, pretty simple.  Supporting modifications in the CLI was a little harder, as it requires "resolving" things like "depends:5" to a UUID, which requires a replica.  But that wasn't too bad, either.
The vritual tags support has me a little stumped, though.  +BLOCKED requires looking at the depended-on task to see if it's still pending.  That's not so bad, but requires a reference to the replica, which most `Task` methods do not (`TaskMut` does, but this isn't a mutation..).  +BLOCKING is even worse, though: it requires, I think, a full scan of the taskdb.
I'll look at how TaskWarrior implements these things.
> Add support for dependencies

- README.md
- integration-tests/build.rs
- lib/Cargo.toml
- lib/src/lib.rs
- lib/src/string.rs
This puts all of the symbols at the top level, and publishes the crate as an rlib.
I suspect this will be the easiest way to make this C code available elsewhere?  At any rate, it was the simplest way I could find to integrate with Taskwarrior.
> export taskchampion-lib as an rlib, too
